### PR TITLE
New and animated Death Knight model

### PR DESCRIPTION
**Pull request by Nolcoz**
Model by Mr.M, texture by @pnahratow and animations by me. Note that the unused animations the original Death Knight had, have not been fully animated

### CODE REVIEW

**Review by MissLavender-LQ — COMMENTED** [review]
### looks good to me
https://github.com/MissLavender-LQ/LibreQuake/assets/51702517/cbee4851-8e95-4c0d-9223-eee2469d6f2a

**Review by MissLavender-LQ — APPROVED** [review]

**Comment by MotoLegacy** [comment]
> Note that the unused animations the original Death Knight had, have not been fully animated

Is this something we'd want? I'm sure there are mods that potentially restore it as "unused content", or whatever.

**Comment by Nolcoz** [comment]
That is a really fair point ye. Those unused animations can be simply added later its just that I wanted to first finish the ones that are used in game first. I could try and do those ones later, but not now tbh gonna start to get more busy now

**Comment by MotoLegacy** [comment]
> That is a really fair point ye. Those unused animations can be simply added later its just that I wanted to first finish the ones that are used in game first. I could try and do those ones later, but not now tbh gonna start to get more busy now

Sure thing. @MissLavender-LQ do we have anywhere public and easily accessible so we can document the specific status on this? I will merge if so. Let's discuss options for publishing that information here.

**Comment by Nolcoz** [comment]
I could put that the unused animations are not finished in the title of the pull if that helps

**Comment by MotoLegacy** [comment]
Ideally we'd want it in a comprehensive TODO list, like I had been doing for sounds.

**Comment by Nolcoz** [comment]
Ah thats fair then

**Comment by MissLavender-LQ** [comment]
> That is a really fair point ye. Those unused animations can be simply added later its just that I wanted to first finish the ones that are used in game first. I could try and do those ones later, but not now tbh gonna start to get more busy now

just send me the old blend and ill add it to the attic

**Comment by Nolcoz** [comment]
What do you mean old blend file? If you mean about the one with the unfinished unused animations then its the current one. If you want that one, its on the download room

**Comment by MissLavender-LQ** [comment]
> What do you mean old blend file? If you mean about the one with the unfinished unused animations then its the current one. If you want that one, its on the download room

ah heard

**Comment by MissLavender-LQ** [comment]
>Sure thing. @MissLavender-LQ do we have anywhere public and easily accessible so we can document the specific status on this? I will merge if so. Let's discuss options for publishing that information here.

i need some clarification im not understanding 
do we have a list for unused animations? no
do we have a list for what assets are finished?  yes but its out of date **[[asset list]](https://scalar.vector.im/etherpad/p/LQ_Assets_6D8gJa8PnOaMl49j)**

**Comment by MissLavender-LQ** [comment]
ok but we shouldnt do that on this pull req lets move this to an issue

**Review by RandomBrushes — APPROVED** [review]
Looks good to me

**Pull request merged**
