### PR TITLE
new low detail health packs

### PR DESCRIPTION
**Pull request by MissLavender-LQ**

### CODE REVIEW

**Review by MotoLegacy — APPROVED** [review]
Seems like you've committed some build script stuff too, particularly with PAK file casing. Consider in the future making these separate PRs, otherwise LGTM.

**Comment by MissLavender-LQ** [comment]
> Seems like you've committed some build script stuff too, particularly with PAK file casing. Consider in the future making these separate PRs, otherwise LGTM.


LGTM?

**Comment by MotoLegacy** [comment]
> LGTM?

Looks good to me!

**Comment by Ospaggi** [comment]
> > Seems like you've committed some build script stuff too, particularly with PAK file casing. Consider in the future making these separate PRs, otherwise LGTM.
> 
> 
> LGTM?
> 

that means 'Looks Good To Me.'

**Pull request merged**
