### PR TITLE
Updates to Backpack and boss models

### PR DESCRIPTION
**Pull request by MissLavender-LQ**
# [New LibreQuake Backpack texture]
### there is some dif between @pnahratow 's final bag texture and the one here since i needed to rebake it to a new uv map i had done 
https://github.com/MissLavender-LQ/LibreQuake/assets/51702517/d57a4e81-3710-4ba9-9db0-de92d7b470d8
128-rebake

# [New LibreQuake Boss Uv/Texture]
### Updated Texture / Uv map for a 1024x256 texture
https://github.com/MissLavender-LQ/LibreQuake/assets/51702517/5de421e8-3355-4abc-b532-d160d3e4f3b5

image

### CODE REVIEW

**Review by MotoLegacy — APPROVED** [review]
LGTM

**Comment by MissLavender-LQ** [comment]
yay

**Comment by MissLavender-LQ** [comment]
texture is dif

**Comment by MotoLegacy** [comment]
> texture is dif

"dif" resolution? That'd be the only reason it would increase if the mesh is unmodified.

**Comment by MissLavender-LQ** [comment]
then im not sure will check

**Comment by MissLavender-LQ** [comment]
(1) being the newer one 
image
ohhh i think its because i did a slight change to the uv

**Review by RandomBrushes — APPROVED** [review]
Looks good to me!

**Pull request merged**
