### PR TITLE
new host_timescale dev binds

### PR DESCRIPTION
**Pull request by MissLavender-LQ**
] = game speed up

[ = game speed down

' = game speed reset

## in game showcase
https://github.com/MissLavender-LQ/LibreQuake/assets/51702517/8e6c721f-f34f-4dc1-a853-6405757ed7b4

### CODE REVIEW

**Review by MotoLegacy — COMMENTED** [review]
Is there really not a way to perform incremental changes via a config file? You can do some really funky stuff sometimes.

**Comment by MotoLegacy** [comment]
Additionally, please justify the need for this to be a configuration bind to begin with, as opposed to general console use. Thanks.

**Comment by MissLavender-LQ** [comment]
> Additionally, please justify the need for this to be a configuration bind to begin with, as opposed to general console use. Thanks.

there has been multiple times i quickly wanna speed up the game to lets say clear a power up effect faster or noclip through a map faster 
and
there is times where i wanna quickly slow down the game to show case an animation or some aspect of game play in a map

especially with the speed up side of it 
it would just take to much time to justify typing it out

**Comment by MissLavender-LQ** [comment]
> Is there really not a way to perform incremental changes via a config file? You can do some really funky stuff sometimes.

the only thing that gets close to that is "bind toggle" and that only swaps between 1 and 0, so no sadly

**Review by MotoLegacy — APPROVED** [review]

**Review by RandomBrushes — APPROVED** [review]
Looks good to me!

**Pull request merged**
